[binance]
enabled = true
base_url = "http://127.0.0.1:19000"
max_order_value_usd = 100.0
daily_volume_cap_usd = 200.0
allow_delete_open_orders = false
recv_window_ms = 5000

[custom.github]
base_url = "http://127.0.0.1:19000"
auth_header = "Authorization"
auth_value_prefix = "Bearer "
blocked_endpoints = ["DELETE /repos/*", "PUT /repos/*/admin/*", "DELETE /orgs/*"]
rate_limit = 2
rate_limit_window_seconds = 60
