[package]
name = "fishnet-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "fishnet"
path = "src/main.rs"

[dependencies]
fishnet-server = { path = "../server" }
tokio.workspace = true
axum.workspace = true
